### ISSUE TITLE
Could not run test_installation.sh

### ISSUE THREAD

**Issue by EmilyN12** [cbib/virhunter#8]
I downloaded VirHunter and its required python packages, but when I tested it out it output following error:

> scripts/test_installation.sh: line 2: 31617 Aborted                 python virhunter/prepare_ds.py configs/test_installation_config.yaml
> finished preparation of training dataset for neural network and random forest modules
> number in the brackets corresponds to the GPU being used; empty brackets - no GPU usage
> []
> Traceback (most recent call last):
>   File "virhunter/train.py", line 244, in <module>
>     fire.Fire(train)
>   File "/home/hning/ENV/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/home/hning/ENV/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/home/hning/ENV/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "virhunter/train.py", line 224, in train
>     train_nn(
>   File "virhunter/train.py", line 93, in train_nn
>     f = h5py.File(Path(ds_path, f"encoded_train_{length}.hdf5"), "r")
>   File "/home/hning/ENV/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
>     fid = make_fid(name, mode, userblock_size,
>   File "/home/hning/ENV/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 88, in h5py.h5f.open
> OSError: Unable to open file (unable to open file: name = 'test_installation_out/train_ds/encoded_train_500.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
> finished training neural network and random forest modules
> starting prediction for viruses.fasta for fragment length 500
> scripts/test_installation.sh: line 6: 32170 Aborted                 python virhunter/predict.py configs/test_installation_config.yaml
> finished prediction of the test file
> If there were no errors, VirHunter works properly!

I checked the link to the toy data, there were only 3 fasta files for the virus etc. I am wondering if this is a bug.

**Comment by gregoruar** [comment]
Hi!
I retested the installation and evertything works fine on my side.
It seems the problem comes from the fact that the job of preparing datasets for the network is aborted (the very first line)
And since no datasets are prepared you cannot test the model.
Abort often means the process is interrupted by the user, so you can try rerunning the script.
If you do not find the error you can still try running the predictions, hopefully, they will work.

**Comment by EmilyN12** [comment]
> Hi! I retested the installation and evertything works fine on my side. It seems the problem comes from the fact that the job of preparing datasets for the network is aborted (the very first line) And since no datasets are prepared you cannot test the model. Abort often means the process is interrupted by the user, so you can try rerunning the script. If you do not find the error you can still try running the predictions, hopefully, they will work.


Hi,

I tried to find the error but I couldn't so right now I am running the predictions directly. I have one question.

How do you test the predictions for a pair-end sample in FASTQ format? From the script in the configs folder, I could only deduce how to do predictions for single-end FASTQ or FASTA file (path to file on each line if testing multiple files). What about pair-end FASTQ files? Do I still write the path to each file in the following format?

```
predict:
    test_ds: 
        - /path/to/pair/end/sample1_R1.fastq
        - /path/to/pair/end/sample1_R2.fastq
        - /path/to/pair/end/sample2_R1.fastq
        - /path/to/pair/end/sample2_R2.fastq
        - /path/to/pair/end/sample3_R1.fastq
        - /path/to/pair/end/sample3_R2.fastq
```

**Comment by tigloo123** [comment]
Please note that VirHunter is expressly designed to work with assembled as input. So prior to running VirHunter you should assemble your reads
